Default: &defaults
  user: tersus
  password: tersus-pw!
  host: localhost
  port: 27017
  database: tersus
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: tersus_test
  <<: *defaults

Staging:
  database: tersus_staging
  poolsize: 100
  <<: *defaults

Production:
  database: tersus_production
  poolsize: 100
  <<: *defaults
